name: mi_card_flutter_2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/ironman.jpg
  fonts:
    - family: Charmonman
      fonts:
        - asset: fonts/Charmonman-Regular.ttf

    - family: Source Sans
      fonts:
        - asset: fonts/SourceSans3.ttf

    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

